apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartoons-deployment
spec:
  selector:
    matchLabels:
      app: cartoons-server
  replicas: 2
  template:
    metadata:
      labels:
        app: cartoons-server
    spec:
      containers:
      - name: cartoons-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/jairdelfin/cartoons:9f2efa753af6194c074f5a40687f9ff60bbedfad
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  labels:
    run: cartoons-service
  name: cartoons-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cartoons-server
  type: LoadBalancer
